/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: a2e4e49189d127526d69032df3e47243)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject";
	}
	interface IntegrationEnv {
		rezept_recipe_uploads: R2Bucket;
		rezept_recipe_scrapes: R2Bucket;
		rezept_core: D1Database;
		ASSETS: Fetcher;
		WEBAUTHN_APP_NAME: "rezept";
		REZEPT_ENV: "integration";
		VITE_BASE_URL: "https://rezept-integration.arsdehnel.workers.dev";
		SESSION_SECRET_KEY: string;
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	}
	interface StagingEnv {
		rezept_recipe_scrapes: R2Bucket;
		ASSETS: Fetcher;
		WEBAUTHN_APP_NAME: "rezept";
		REZEPT_ENV: "staging";
		VITE_BASE_URL: "https://rezept-staging.arsdehnel.workers.dev";
		SESSION_SECRET_KEY: string;
	}
	interface ProductionEnv {
		rezept_recipe_scrapes: R2Bucket;
		ASSETS: Fetcher;
		WEBAUTHN_APP_NAME: "rezept";
		REZEPT_ENV: "production";
		VITE_BASE_URL: "https://rezept.arsdehnel.workers.dev";
		SESSION_SECRET_KEY: string;
	}
	interface Env {
		rezept_recipe_uploads?: R2Bucket;
		rezept_recipe_scrapes: R2Bucket;
		rezept_core?: D1Database;
		ASSETS: Fetcher;
		WEBAUTHN_APP_NAME: "rezept";
		REZEPT_ENV: "integration" | "staging" | "production" | "development";
		VITE_BASE_URL?: "https://rezept-integration.arsdehnel.workers.dev" | "https://rezept-staging.arsdehnel.workers.dev" | "https://rezept.arsdehnel.workers.dev";
		SESSION_SECRET_KEY: string;
		SESSION_DURABLE_OBJECT?: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBAUTHN_APP_NAME" | "REZEPT_ENV" | "VITE_BASE_URL" | "SESSION_SECRET_KEY">> {}
}
