/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 272e582154776998548defc9783dbac0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject";
	}
	interface Env {
		WEBAUTHN_APP_NAME: "rezept";
		WEBAUTHN_RP_ID: string;
		AUTH_SECRET_KEY: string;
		REZEPT_ENV: string;
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		rezept_recipe_imports: R2Bucket;
		rezept_core: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBAUTHN_APP_NAME" | "WEBAUTHN_RP_ID" | "AUTH_SECRET_KEY" | "REZEPT_ENV">> {}
}
