/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 29bdfb1bb831aa2ff9d20879d326abe9)
interface __BaseEnv_Env {
	REZEPT_RECIPE_UPLOADS: R2Bucket;
	REZEPT_RECIPE_SCRAPES: R2Bucket;
	REZEPT_IMAGES: R2Bucket;
	REZEPT_CORE: D1Database;
	AED_LOGIN_ATTEMPTS: AnalyticsEngineDataset;
	AED_API_KEY_USED: AnalyticsEngineDataset;
	AED_SCRAPE_ATTEMPTS: AnalyticsEngineDataset;
	ASSETS: Fetcher;
	WEBAUTHN_APP_NAME: "rezept";
	REZEPT_ENV: "integration" | "staging" | "production" | "development";
	LOG_LEVEL: "info" | "debug";
	LOG_LEVEL_TASK_OVERRIDE: "";
	SESSION_SECRET_KEY: string;
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	RECIPE_SCRAPE_COVER_IMAGE_RETRY_WORKFLOW: Workflow<Parameters<import("./src/worker").RecipeScrapeCoverImageRetryWorkflow['run']>[0]['payload']>;
	RECIPE_RAW_INGREDIENTS_TO_INGREDIENTS_WORKFLOW?: Workflow<Parameters<import("./src/worker").RecipeRawIngredientsToIngredientsWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject";
	}
	interface IntegrationEnv {
		REZEPT_RECIPE_UPLOADS: R2Bucket;
		REZEPT_RECIPE_SCRAPES: R2Bucket;
		REZEPT_IMAGES: R2Bucket;
		REZEPT_CORE: D1Database;
		AED_LOGIN_ATTEMPTS: AnalyticsEngineDataset;
		AED_API_KEY_USED: AnalyticsEngineDataset;
		AED_SCRAPE_ATTEMPTS: AnalyticsEngineDataset;
		ASSETS: Fetcher;
		WEBAUTHN_APP_NAME: "rezept";
		REZEPT_ENV: "integration";
		LOG_LEVEL: "info";
		LOG_LEVEL_TASK_OVERRIDE: "";
		SESSION_SECRET_KEY: string;
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		RECIPE_SCRAPE_COVER_IMAGE_RETRY_WORKFLOW: Workflow<Parameters<import("./src/worker").RecipeScrapeCoverImageRetryWorkflow['run']>[0]['payload']>;
	}
	interface StagingEnv {
		REZEPT_RECIPE_UPLOADS: R2Bucket;
		REZEPT_RECIPE_SCRAPES: R2Bucket;
		REZEPT_IMAGES: R2Bucket;
		REZEPT_CORE: D1Database;
		AED_LOGIN_ATTEMPTS: AnalyticsEngineDataset;
		AED_API_KEY_USED: AnalyticsEngineDataset;
		AED_SCRAPE_ATTEMPTS: AnalyticsEngineDataset;
		ASSETS: Fetcher;
		WEBAUTHN_APP_NAME: "rezept";
		REZEPT_ENV: "staging";
		LOG_LEVEL: "info";
		LOG_LEVEL_TASK_OVERRIDE: "";
		SESSION_SECRET_KEY: string;
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		RECIPE_SCRAPE_COVER_IMAGE_RETRY_WORKFLOW: Workflow<Parameters<import("./src/worker").RecipeScrapeCoverImageRetryWorkflow['run']>[0]['payload']>;
	}
	interface ProductionEnv {
		REZEPT_RECIPE_UPLOADS: R2Bucket;
		REZEPT_RECIPE_SCRAPES: R2Bucket;
		REZEPT_IMAGES: R2Bucket;
		REZEPT_CORE: D1Database;
		AED_LOGIN_ATTEMPTS: AnalyticsEngineDataset;
		AED_API_KEY_USED: AnalyticsEngineDataset;
		AED_SCRAPE_ATTEMPTS: AnalyticsEngineDataset;
		ASSETS: Fetcher;
		WEBAUTHN_APP_NAME: "rezept";
		REZEPT_ENV: "production";
		LOG_LEVEL: "info";
		LOG_LEVEL_TASK_OVERRIDE: "";
		SESSION_SECRET_KEY: string;
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		RECIPE_SCRAPE_COVER_IMAGE_RETRY_WORKFLOW: Workflow<Parameters<import("./src/worker").RecipeScrapeCoverImageRetryWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBAUTHN_APP_NAME" | "REZEPT_ENV" | "LOG_LEVEL" | "LOG_LEVEL_TASK_OVERRIDE" | "SESSION_SECRET_KEY">> {}
}
