import fs from 'node:fs/promises';
import path from 'node:path';
import chalk from 'chalk-template';

let content = `# Server Actions

This file is generated by \`scripts/docs/actions.ts\`, any changes made manually will be overridden.

`;

function actionTemplate(actionName: string, requiresAuth: boolean, perms: string[]) {
	return `### ${actionName}

- **Require Auth:** ${requiresAuth ? '✅' : '🚫'}
- **Permissions Required (at least one):** ${perms.length > 0 ? perms.join(', ') : 'none'}

`;
}

export default async function actionsDocs() {
	const allActionFiles = (await fs.readdir(path.join(process.cwd(), 'src/actions'))).filter(
		f => f.endsWith('.ts') && !f.endsWith('utils.ts'),
	);
	const docsFilePath = path.join(process.cwd(), 'src/actions', 'generated.md');

	console.log(chalk`\nFound {cyan ${allActionFiles.length}} action files`);

	for (const actionFilePath of allActionFiles) {
		console.log(chalk`\n Reading {yellow ${actionFilePath}}`);
		content += `## ${actionFilePath}\n\n`;

		const fileContents = (await fs.readFile(path.join(process.cwd(), 'src/actions', actionFilePath))).toString();

		//  _______ _______ _______ __   _ ______  _______         _____  __   _ _______      _______ _     _  _____   _____   ______ _______ _______ ______       _______ _     _ __   _ _______ _______ _____  _____  __   _ _______
		//  |______    |    |_____| | \  | |     \ |_____| |      |     | | \  | |______      |______  \___/  |_____] |     | |_____/    |    |______ |     \      |______ |     | | \  | |          |      |   |     | | \  | |______
		//  ______|    |    |     | |  \_| |_____/ |     | |_____ |_____| |  \_| |______      |______ _/   \_ |       |_____| |    \_    |    |______ |_____/      |       |_____| |  \_| |_____     |    __|__ |_____| |  \_| ______|
		//
		const exportedFunctionNames = [...fileContents.matchAll(/^export async function ([^_]\w*)/gm)].map(m => String(m[1]));

		exportedFunctionNames.forEach(actionName => {
			content += actionTemplate(actionName, false, []);
		});

		//  _______ _______  ______ _    _ _______  ______      _______ _______ _______ _____  _____  __   _ _______
		//  |______ |______ |_____/  \  /  |______ |_____/      |_____| |          |      |   |     | | \  | |______
		//  ______| |______ |    \_   \/   |______ |    \_      |     | |_____     |    __|__ |_____| |  \_| ______|
		//
		const serverActionDefinitions = [...fileContents.matchAll(/serverAction\(\[([\s\S]*?)\]\)/g)].map(m =>
			String(m[1]).replaceAll('\n', '').replaceAll('\t', ''),
		);

		serverActionDefinitions.forEach(def => {
			const requiresAuth = def.includes('requireAuthentication');
			const actionName = def
				.split(',')
				.filter(Boolean)
				.map(i => i.trim())
				.pop()
				?.slice(1);

			const permMatch = def.match(/requirePermissions\(([^)]*)\)/);
			let perms: string[] = [];
			if (permMatch) {
				perms = [...permMatch[1].matchAll(/'([^']+)'/g)].map(m => m[1]);
				// ['seasons:create', 'seasons:update']
			}

			if (!actionName) {
				throw new Error(`No action name parsed`);
			}

			content += actionTemplate(actionName, requiresAuth, perms);
		});
	}
	await fs.writeFile(docsFilePath, content, 'utf-8');
	console.log(chalk`Generated docs written to {green ${docsFilePath}}`);
}
