import fs from 'node:fs/promises';
import path from 'node:path';
import chalk from 'chalk-template';
import type { Permission } from '@/types';

let content = `# APIs

This file is generated by \`scripts/docs/apis.ts\`, any changes made manually will be overridden.

`;

function apiTemplate(apiPath: string, apiVerb: string, requiresAuth: boolean, perms: Permission[]) {
	return `### ${apiVerb.toUpperCase()} ${apiPath}

- **Require Auth:** ${requiresAuth ? '✅' : '🚫'}
- **Permissions Required (at least one):** ${perms.length > 0 ? perms.join(', ') : 'none'}

`;
}

export default async function apiDocs() {
	const allApiFiles = (await fs.readdir(path.join(process.cwd(), 'src/api'), { recursive: true })).filter(
		f => f.endsWith('.ts') && !f.endsWith('utils.ts') && !f.endsWith('routes.ts') && !f.includes('__tests__'),
	);
	const docsFilePath = path.join(process.cwd(), 'src/api', 'generated.md');

	console.log(chalk`\nFound {cyan ${allApiFiles.length}} api files`);

	for (const apiFilePath of allApiFiles) {
		console.log(chalk`\n Reading {yellow ${apiFilePath}}`);
		content += `## ${apiFilePath}\n\n`;

		const apiPath = `/${apiFilePath.replace('.ts', '')}/`;
		const fileContents = (await fs.readFile(path.join(process.cwd(), 'src/api', apiFilePath))).toString();

		const exportedFunctionNames = [...fileContents.matchAll(/^export default \{[\s\S]*?\}/gm)].map(match => match[0]);
		exportedFunctionNames.forEach(funcBlock => {
			const methods = funcBlock.split('\n').slice(1, -1);
			methods.forEach(method => {
				const [verb, handlerArray] = method.trim().split(/:(.*)/s);
				const requiresAuth = handlerArray.includes('requireAuthentication');
				const permMatch = handlerArray.match(/requirePermissions\(([^)]*)\)/);
				let perms: Permission[] = [];
				if (permMatch) {
					perms = [...permMatch[1].matchAll(/'([^']+)'/g)].map(m => m[1]) as Permission[];
				}
				content += apiTemplate(apiPath, verb, requiresAuth, perms);
			});
		});
	}
	await fs.writeFile(docsFilePath, content, 'utf-8');
	console.log(chalk`Generated docs written to {green ${docsFilePath}}`);
}
