import fs from 'node:fs/promises';
import path from 'node:path';
import chalk from 'chalk-template';

let content = `# Pages

This file is generated by \`scripts/docs/pages.ts\`, any changes made manually will be overridden.

`;

function pageTemplate(routePath: string, requiresAuth: boolean, perms: string[]) {
	return `### ${routePath}

- **Require Auth:** ${requiresAuth ? '✅' : '🚫'}
- **Permissions Required:** ${perms.length > 0 ? perms.join(', ') : 'none'}

`;
}

export default async function pagesDocs() {
	const allRoutesFiles = (await fs.readdir(path.join(process.cwd(), 'src/pages'), { recursive: true }))
		.filter(f => f.endsWith('routes.ts'))
		.sort();
	const docsFilePath = path.join(process.cwd(), 'src/pages', 'generated.md');

	console.log(chalk`\nFound {cyan ${allRoutesFiles.length}} routes files`);

	for (const routesFilePath of allRoutesFiles) {
		console.log(chalk`\n Reading {yellow ${routesFilePath}}`);
		content += `## ${routesFilePath}\n\n`;

		// Derive the URL prefix from the directory name (e.g. recipes/routes.ts → /recipes)
		const prefix = `/${routesFilePath.replace('/routes.ts', '')}`;
		const fileContents = (await fs.readFile(path.join(process.cwd(), 'src/pages', routesFilePath))).toString();

		// Routes with handler arrays — may include requireAuthentication / requirePermissions
		[...fileContents.matchAll(/\broute\((['"][^'"]*['"]),\s*\[([\s\S]*?)\]/g)].forEach(m => {
			const routePath = m[1].slice(1, -1);
			const handlerArray = m[2];
			const requiresAuth = handlerArray.includes('requireAuthentication');
			const permMatch = handlerArray.match(/requirePermissions\(([^)]*)\)/);
			const perms = permMatch ? [...permMatch[1].matchAll(/'([^']+)'/g)].map(p => p[1]) : [];
			const fullPath = routePath === '/' ? prefix : `${prefix}${routePath}`;
			content += pageTemplate(fullPath, requiresAuth, perms);
		});

		// Routes without handler arrays (public — no interrupters)
		[...fileContents.matchAll(/\broute\((['"][^'"]*['"]),(?!\s*\[)/g)].forEach(m => {
			const routePath = m[1].slice(1, -1);
			const fullPath = routePath === '/' ? prefix : `${prefix}${routePath}`;
			content += pageTemplate(fullPath, false, []);
		});
	}

	await fs.writeFile(docsFilePath, content, 'utf-8');
	console.log(chalk`Generated docs written to {green ${docsFilePath}}`);
}
