name: Feature Request
description: Propose a new feature or enhancement.
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: textarea
    id: context
    attributes:
      label: Additional Context