name: Idea
description: A rough idea or shower thought — not fully baked yet.
title: "[Idea]: "
labels: ["idea"]
body:
  - type: textarea
    id: idea
    attributes:
      label: The Idea
      description: Describe it however you'd like — rough is fine.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Why / Inspiration
      description: What prompted this? Any context that might help the discussion.