export default [
	'2  Yellow Plantains (peeled)',
	'Vegetable Oil (for frying)',
	'Sea salt (to taste)',
	'½ lb dry penne',
	'1 cup chicken broth',
	'2 cups marinara sauce',
	'2 tsp minced garlic',
	'½ tsp salt',
	'¼ tsp pepper',
	'1.5 tsp oregano',
	'1 tsp rosemary',
	'½ tsp sage',
	'½ tsp marjoram',
	'3 oz Pepperoni',
	'1 cup shredded mozzarella',
	'2 tbsp olive oil',
	'½ tbsp garlic (minced)',
	'1  yellow onion (diced)',
	'4  medium beets (about 1 lb) (peeled and cut into thin matchsticks)',
	'2 cups shredded green or red cabbage',
	'3  carrots (peeled and shredded)',
	'1 tsp granulated sugar',
	'¼ cup tomato paste (about ½ of a 6 oz can)',
	'6 cups vegetable broth',
	'2  medium russet potatoes (peeled & cubed)',
	'1 tbsp white vinegar',
	'1 tbsp fresh dill',
	'1 tsp table salt',
	'1 tsp pepper',
	'½ cup canned tomato sauce',
	'Sour cream (for garnishment)',
	'Fresh dill weed (for garnishment)',
	'2 cups water',
	'½ cup water (extra)',
	'½ cup rice',
	'2 tbsp peanut butter (I used Jif)',
	'2 tbsp whole wheat flour',
	'Peanut Butter',
	'Banana slices',
	'Brown sugar',
	'Baguette',
	'Horseradish Gouda Cheese',
	'Tomato',
	'Mustard',
	'Salami',
	'Olive Tapenade',
	'Mint leaves',
	'Dijon Mustard',
	'Pickles',
	'Prosciutto',
	'Salami',
	'Red Peppers',
	'Horseradish',
	'1 cup Heavy Whipping Cream',
	'1 cup Pesto',
	'1 cup Chicken broth',
	'1/2 lb Rotini',
	'1 cup Parmesan Cheese',
	'1  box pepperidge farm puff pastry sheets',
	'1 lb jimmy deans sausage (ground)',
	'1  carrot (shredded)',
	'1  onion (diced finely)',
	'¾ cup Italian bread crumbs',
	'⅓ cup milk',
	'2 tsp minced garlic',
	'Salt and pepper',
	'2 tbsp barbeque sauce',
	'1  egg',
	'1 tbsp water',
	'Paprika',
	'2 lb russet potatoes (peeled and chopped into eighths)',
	'Water',
	'¼ cup milk',
	'1 tsp chopped garlic',
	'¼ tsp salt',
	'Fresh Ground Black Pepper to Taste',
	'½  recipe for Cuban Picadillo',
	'1 cup breadcrumbs',
	'2  eggs',
	'Sunflower oil or Vegetable Oil for Frying',
	'3 tbsp olive oil',
	'1   medium yukon gold potato (diced)',
	'1  small onion (diced)',
	'1  bell pepper (green preferred)  (diced)',
	'2 tsp garlic (minced)',
	'3/4 tsp ground oregano',
	'15 oz can tomato sauce',
	'1/4  cup  raisins',
	'1 lb ground beef',
	'salt and pepper (to taste)',
	'1/2 cup green olives (sliced)',
	'2 tbsp olive juice',
	'2 tbsp-1/4 cup  white wine (depending on preference )',
	'1 tbsp ghee (divided)',
	'¼ cup raisins',
	'3  green cardamom pods',
	'1  cinnamon stick',
	'2 tbsp chopped almonds',
	'2 tbsp chopped pistachios',
	'1 cup vermicelli',
	'3 cups whole milk',
	'½ tsp saffron threads',
	'3 tbsp granulated sugar',
	'⅛ tsp salt',
	'1 Tbsp korerima',
	'1 lb unsalted butter',
	'2 Tbsp koseret',
	'1 Tbsp besobela',
	'¼ tsp ground turmeric',
	'1 Tbsp freshly minced garlic',
	'1 Tbsp freshly minced ginger',
	'1 cup yellow split peas',
	'1 tsp turmeric',
	'1 tsp fennel seeds',
	'½ tsp cumin',
	'2 cups + 6 Tbsp all purpose flour',
	'1½ tsp salt (divided)',
	'Vegetable oil',
	'3¼ lb chicken legs and thighs (bone in, skin off )',
	'1½ tsp salt',
	'2 tsp fresh grated ginger',
	'2 tsp fresh grated garlic',
	'1 tsp ground turmeric',
	'½  large yellow onion (diced)',
	'2 tbsp vegetable oil',
	'3  cinnamon sticks',
	'2 cups canned crushed tomatoes',
	'2-3  sliced chili peppers (optional)',
	'1 (15 oz) can unsweetened coconut milk',
	'1 cup sugar',
	'¾ cup water',
	'2 cups unsalted peanuts (roasted)',
	'1 tsp cinnamon',
	'½ tsp vanilla',
	'¼ tsp salt',
	'¼ tsp nutmeg',
	'⅛ tsp cayenne (optional)',
	'1/2 cup unsalted butter (softened)',
	'1 cup brown sugar',
	'1  large egg',
	'1 teaspoon vanilla extract',
	'1 cup all-purpose flour',
	'1/4 teaspoon salt',
	'1/2 teaspoon baking soda',
	'1 cup sesame seeds',
	'2 cups white cornmeal',
	'5 cups water',
	'2 Tbsp vegetable oil',
	'2  small red onions (diced)',
	'4 cloves garlic (minced)',
	'4  small roma tomatoes (diced)',
	'16 cups greens (I used a blend of kale, rainbow chard, and dandelion greens)',
	'1/2  cup water',
	'Salt to taste',
	'4  red onions (finely chopped)',
	'¼ cup vegetable oil',
	'1 Tbsp Garlic paste',
	'1 Tbsp Ginger paste',
	'3 tbsp tomato paste',
	'1 tsp cardamom',
	'1 tsp salt (more or less to taste)',
	'3-4 tbsp berbere (depending on how spicy you want it )',
	'3 tbsp ghee or Niter Kibbeh',
	'2 lbs chicken  (all cuts, bone in, skin removed)',
	'2 cups chicken broth',
	'4  hard boiled eggs (with little slices cut into the whites )',
	'2 tbsp ghee',
	'2 lb bone-in lamb',
	'1  cinnamon stick',
	'4 cups water',
	'⅓ cup granulated sugar',
	'12  pitless prunes (soaked in hot water for two hours)',
	'10  dried apricots (soaked in hot water for two hours)',
	'1  unripe pear (peeled and cut into pipes)',
	'2 tbsp large raisins (soaked in hot water for two hours)',
	'1 ½ tsp orange blossom water',
	'2 tbsp blanched almonds',
	'3 Tbsp vegetable oil (divided)',
	'¾ cup yellow onion (finely diced)',
	'¼ cup green onion',
	'1  russet potato (finely diced)',
	'1  roma tomato (finely diced)',
	'1  red long hot chilli pepper',
	'2 cups finely chopped parsley',
	'1 cup finely chopped cilantro',
	'½ cup milk',
	'8  eggs',
	'3 tablespoons breadcrumbs',
	'3 tablespoons all purpose flour',
	'3 teaspoons baking powder',
	'½ tsp black pepper (more or less to taste)',
	'1 tsp salt (more or less to taste)',
	'1 lb Stew Beef',
	'1 lb Smoked Turkey (bone in (can also use any bone-in chicken))',
	'1½ Tbsp Complete seasoning (divided)',
	'1 cup chopped white onion',
	'1-3  Habanero Peppers',
	'1 tsp Salt',
	'½ tsp black pepper',
	'1½ lb Frozen Bag Cassava Leaf (rinsed, strained and squeezed dry)',
	'2  Beef Maggi cubes',
	'¼ cup creamy peanut butter',
	'1 cup red palm oil',
	'2 Tbsp Ground crayfish (optional)',
	'2 cups 2% or whole milk',
	'1 ½ cups fresh mango (about 1 mango)',
	'3 tbsp granulated sugar',
	'½ cups ice',
	'¼ tsp cardamom',
	'3  Garlic cloves',
	'4  Green onions',
	'14 oz can whole peeled tomatoes (drained)',
	'3  Habanero Pepper or Scotch Bonnet Pepper (divided)',
	'3 Tbsp Vegetable Oil',
	'2 lb boneless stew beef',
	'1  small red onion (chopped)',
	'2 Tbsp tomato paste',
	'4 cups beef or chicken broth',
	'⅔ cup creamy peanut butter',
	'3  Carrots (peeled and cut into thirds)',
	'2  Russet Potatoes (peeled and cut into sixths)',
	'1  Sweet Potato (peeled and cut into sixths)',
	'1  red bell pepper (quartered)',
	'2 Tbsp Vegetable Oil',
	'½  white onion (diced)',
	'2 tsp Garlic (minced)',
	'½  yellow bell pepper (diced)',
	'½  red bell pepper (diced)',
	'½  green bell pepper (diced)',
	'2 tsp Curry Powder',
	'½ tsp Paprika',
	'1 tsp Oregano',
	'2 tsp Complete Seasoning',
	'4 cups carrots (grated, about 4-5 Large carrots)',
	'28  oz Baked Beans',
	'2 Tbsp Sweet Chili sauce',
	'1 cup unsalted butter (softened)',
	'½ cup granulated sugar',
	'1 large  egg',
	'1 tsp vanilla extract',
	'2 ½ cups all purpose flour (more as necessary)',
	'1 tsp baking powder',
	'¼ cup powdered sugar',
	'½ cup raspberry jam  (or preserve of your choice)',
	'¼ tsp saffron',
	'¼ cup boiling water',
	'1  Preserved Lemon',
	'¼ cup parsley (finely chopped )',
	'¼ cup cilantro (finely chopped )',
	'4  garlic cloves (grated)',
	'2 tsp Ground paprika (not smoked paprika)',
	'¾ tsp Ground ginger',
	'½ tsp Cumin',
	'½ tsp ground coriander',
	'¼ tsp black pepper',
	'6 tbsp Olive oil (divided)',
	'2.5 lb chicken thighs and legs (bone-in skin-on )',
	'2  yellow onions (sliced very thinly)',
	'½ tsp turmeric',
	'½ tsp reserved liquid from preserved lemons',
	'½ cup pitted green olives',
	'½ cup Ginger root  (fresh grated)',
	'3 cups Boiling water',
	'½ cup granulated Sugar',
	'1 tsp whole Cloves',
	'2  Cinnamon sticks',
	'¼ cup Lime juice ( fresh squeezed)',
	'½ cup Orange juice  (fresh squeezed)',
	'4 cups Cool water',
	'½ tbsp salt (+ 1 tsp)',
	'1 tbsp black pepper',
	'3 tbsp olive oil',
	'1 tbsp garlic paste',
	'1 tbsp ginger paste',
	'2 lb Goat Ribs',
	'½  red onion (finely into semi circles)',
	'½ cup cilantro (chopped)',
	'1  English cucumber (cut into semi circles)',
	'3  Roma tomatoes (sliced into semi circles with seeds removed)',
	'1  lemon',
	'1  green chili pepper (optional)',
	'Salt (to taste)',
	'2 tbsp vegetable oil',
	'½  red onion (finely diced)',
	'1 large  ripe tomato (diced (can also use 2 ripe roma tomatoes, diced))',
	'Salt (to taste)',
	'1  beef bouillon cube (or 1 tsp of powdered bouillon, optional)',
	'8 cups Collard greens (sliced very finely into small shreds)',
	'8 oz Ditalini  (dry; or elbow noodles)',
	'1 ½ cups Medium grain white rice (dry)',
	'2 15 oz Chickpeas (drained and rinsed)',
	'2  Yellow onions (sliced thinly)',
	'Sunflower oil for frying',
	'2 tbsp Sunflower oil (reserved from frying the onions)',
	'1 ¼ cup Dried brown lentils (rinsed)',
	'4 cups Water',
	'2 tbsp Sunflower oil (reserved from frying the onions)',
	'2 cloves Garlic (minced)',
	'1 15 oz Tomato sauce',
	'1 6 oz Tomato paste',
	'2 cups Water',
	'¼ cup White vinegar',
	'Salt (to taste)',
	'1 tbsp Sunflower oil (reserved from frying the onions)',
	'1 tsp Crushed garlic',
	'½ tbsp Ground cumin',
	'⅓ cup Boiling Water',
	'3 tbsp White vinegar',
	'½ tsp Salt',
	'6  eggs',
	'Water',
	'1 tbsp coffee grounds',
	'1 tbsp olive oil',
	'Skin from 2 white onions',
	'8 cups water',
	'½ cup dried hibiscus flowers',
	'5  basil leaves',
	'10  strawberries (whole)',
	'½  lime (juiced)',
	'¼ cup honey',
	'3 15 oz chickpeas ( drained and rinsed)',
	'¼ cup olive oil',
	'1 tsp garlic (minced)',
	'1 tsp cumin',
	'1 tsp paprika',
	'½ tsp harissa (or more to taste (optional))',
	'1 tbsp tomato sauce',
	'Salt and Pepper to taste',
	'4 cups water (divided)',
	'1 tsp dried mint',
	'1 sprig fresh mint (for garnish)',
	'1  Avocado (cut into cubes)',
	'5 oz Canned Tuna',
	'2 tbsp + 1 ½ tsp   Coconut (unsweetened and grated)',
	'3 tbsp Evaporated Milk',
	'3 tbsp Tomato Sauce',
	'¼ tsp Salt',
	'¼ tsp Pepper',
	'1  Lemon (quartered)',
	'3  Yams (peeled and cubed)',
	'¼ cup Red Palm Oil',
	'1  Red onion (finely diced)',
	'1  Shrimp bouillon cube (I substituted chicken as I couldn’t find shrimp)',
	'Sea salt to taste',
	'2-3  Hard boiled eggs',
	'1/3 cup olive oil',
	'1  medium onion (chopped)',
	'4  roma tomatoes (chopped)',
	'3 cloves garlic (chopped)',
	'2  beef or chicken bouillon cubes ((I prefer beef))',
	'3  bay leaves',
	'1 1/2 cups long grain white rice',
	'3 cups water',
	'16 oz. Tuna steak (cut into ½ inch cubes)',
	'Salt and pepper to taste',
	'2 tbsp Vegetable oil',
	'2 lb sirloin steak (or any other kind of meat that you want. You can also do lamb, etc cut into large, bite sized pieces)',
	'½ tsp Salt',
	'¼ tsp black pepper',
	'1 tsp Better than Bouillon/1 Beef Bouillon Cube',
	'3 tsp yellow Mustard  (+ more for serving)',
	'1  sweet onion (sliced very large into rounds (4 slices))',
	'Cayenne pepper (to taste)',
	'Liquid smoke (optional)',
	'French Baguette (sliced for serving)',
	'2  green plantains',
	'2  yellow/brown plantains',
	'A pinch of salt',
	'3  Medium sized beets',
	'2 tsp salt (divided)',
	'5  medium (gold potatoes, peeled and ch)',
	'1  yellow onion (chopped)',
	'1 ½ tsp ginger',
	'2 tsp garlic',
	'¼ cup vegetable oil',
	'1 tsp ground mustard',
	'1  stalk of rosemary (fresh)',
	'¾ cup red wine',
	'Salt and pepper',
	'2 7 oz filet steaks',
	'2 tbsp butter (divided)',
	'1  onion (chopped)',
	'10  allspice berries (whole)',
	'1 cup white wine',
	'½ cup heavy whipping cream',
	'3/4 cup vegetable oil',
	'2 lb stew beef',
	'1 1/2 tbsp cumin',
	'2 tsp turmeric',
	'1  6 oz can tomato paste (about ½ cup)',
	'1  small red onions (finely diced)',
	'14 oz can finely diced tomatoes (or 4 fresh tomatoes (finely diced))',
	'2 tbsp Berbere',
	'1 tbsp garlic',
	'½  stick unsalted Butter',
	'6  allspice berries',
	'½ tsp cumin seeds',
	'6  green cardamom pods',
	'½ tsp mustard seeds (sub for fenugreek)',
	'⅛ tsp ground cloves',
	'1 tsp ground coriander',
	'1 ½ tbsp paprika',
	'¼ tsp nutmeg',
	'¼ tsp ground cinnamon',
	'2 tbsp cayenne',
	'¼ tsp salt',
	'1 tsp ground ginger',
	'¼  vegetable Oil',
	'½  red onion (minced)',
	'1 tbsp minced garlic',
	'4  plum tomatoes (minced)',
	'2 tbsp tomato paste',
	'1 tsp Berbere',
	'⅓ cup water',
	'6 slices of crusty bread',
	'1  jalapeño',
	'½ cup 5 oz Full fat greek yogurt',
	'4  bananas (cut into 1/2 inch rounds)',
	'⅓ cup orange juice',
	'⅓ cup lemon juice',
	'3 tbsp butter (melted)',
	'¼ cup brown sugar',
	'¼ cup shredded coconut',
	'⅓ tsp Cinnamon',
	'Honey (optional)',
	'2  bananas',
	'3/4 cup all purpose flour',
	'1  egg',
	'¼ cup granulated sugar',
	'¼ tsp salt',
	'½ tsp active dry yeast',
	'¼ cup milk',
	'1 tsp granulated sugar',
	'Vegetable Oil for frying',
	'2 cups Flour',
	'¾ cups Water',
	'½ tsp Salt',
	'1  Onion (chopped)',
	'1 cup leeks (chopped into rounds)',
	'1 tbsp olive oil',
	'½ tsp Cumin',
	'½ tsp Paprika',
	'⅓ tsp Allspice',
	'1 lb Lamb',
	'Salt and pepper to taste',
	'Oil for frying',
	'1 cup uncooked Couscous (“Moroccan”)',
	'½ cup evaporated milk',
	'½ cup vanilla Greek yogurt',
	'¼ cup sour cream',
	'2 tbsp granulated sugar',
	'½ tsp vanilla',
	'¼ tsp nutmeg',
	'½ cup pineapple (canned or fresh)',
	'2 cups flour',
	'½ tsp salt',
	'2 tbsp sugar',
	'1 tbsp cayenne (or more to taste)',
	'1/4 cup vegetable oil',
	'2/3 cup water',
	'2  tuna steaks',
	'Oil (for frying)',
	'1/2 cup all purpose flour',
	'Salt and pepper to taste',
	'2 cups flour',
	'1/4 cup water',
	'1/2 teaspoon salt',
	'1  egg',
	'1 teaspoon active dry yeast (rounded)',
	'7 to 10 oz coconut milk',
	'Butter',
	'Sesame seeds',
	'2  lobster tails (thawed)',
	'4 tbsp butter',
	'3  shallots (minced)',
	'¼ cup white wine',
	'1  vanilla bean',
	'2 tsp vanilla extract',
	'1/4 tsp salt (or more to taste)',
	'½ cup heavy whipping cream',
	'16 oz spinach',
	'2  sweet potatoes on the small side (peeled and shredded)',
	'2  eggs',
	'½ tsp Cinnamon',
	'¼ cup Flour',
	'¼ cup breadcrumbs',
	'Salt and pepper',
	'½ cup tahini',
	'2 tbsp lemon juice',
	'3 tbsp water',
	'¼ tsp salt',
	'½ tsp za’atar',
	'½ cup mayonnaise',
	'⅓ tsp cinnamon',
	'2 tbsp honey',
	'2 cups water',
	'½ cup water (extra)',
	'½ cup rice',
	'2 tbsp peanut butter (I used Jif)',
	'2 tbsp whole wheat flour',
	'Peanut Butter',
	'Banana slices',
	'Brown sugar',
	'5  chicken thighs',
	'Olive oil (for frying )',
	'2  bunch parsley',
	'8  stalks green onions (chopped)',
	'1/2 cup  olive oil',
	'2 inches ginger root (grated)',
	'2 stalks celery (chopped)',
	'2 tsp  garlic (minced)',
	'White pepper to taste',
	'Fresh Ground Black Pepper to Taste',
	'Salt to taste',
	'1  chicken bouillon cube',
	'1  handful green beans (ends trimmed and washed)',
	'1  red bell pepper (chopped)',
	'2  carrots (peeled and sliced into rounds)',
	'3  plantains (slightly ripe, sliced into rounds about one inch thick)',
	'1 c. whole milk',
	'1/4 c. plus 1 tsp. granulated sugar (divided)',
	'1  packet (or 2 1/4 tsp. active dry yeast)',
	'4 c. all-purpose flour (plus more if needed)',
	'1/2 tsp. kosher salt',
	'6 tbsp. melted butter',
	'2  large eggs',
	'1/2 tsp. pure vanilla extract',
	'Sunflower Oil (for frying)',
	'2 cups sugar',
	'½ tsp salt Salt',
	'1/2 cup water',
	'2/3 cup heavy cream',
	'6 tbsp unsalted butter',
	'1 cup semi sweet chocolate chips',
	'5  chicken thighs',
	'1  Onion (chopped)',
	'3  Bay leaves',
	'8 cups Chicken stock',
	'2 stalks Celery (chopped)',
	'2  Carrots (peeled and chopped)',
	'1  Potato (peeled and chopped)',
	'½ cup + 2 tbsp Long grain white rice',
	'4  sprigs fresh Thyme (or more to taste)',
	'½  bunch parsley',
	'White pepper to taste',
	'Garlic powder to taste',
	'Onion powder to taste',
	'Salt to taste',
	'Sprinkle with parmesan cheese',
	'1 stick butter (softened)',
	'2 tbsp butter (melted)',
	'1/4 cup granulated sugar',
	'2  eggs',
	'1 1/2 cups flour',
	'1/4 tsp salt',
	'1 tsp baking powder',
	'2  bananas (sliced into rounds)',
	'1 cup dates (chopped)',
	'1 tbsp sugar',
	'¼ tsp cinnamon',
	'2 tbsp olive oil',
	'1  onion (chopped)',
	'2  cans red beans (drained and rinsed)',
	'2  plantains w black skin (peeled and sliced into 1/2 inch slices)',
	'1 tsp paprika',
	'1 tsp cumin',
	'¾ tsp salt',
	'⅓ tsp cinnamon',
	'1 c chicken stock',
	'1 c water',
	'2 tbsp cilantro',
	'2 pound boneless (skinless chicken thighs)',
	'4  quartered tomatoes',
	'2 cloves garlic',
	'1/2  large onion',
	'1/3 cup olive oil',
	'4 cups chicken stock',
	'1 6 Oz can tomato paste',
	'2 tsp salt',
	'½ tbsp ground red pepper',
	'Sprinkle of parsley',
	'2 1/2 cups long grain white rice',
	'1 tbsp olive oil',
	'1  onion (sliced)',
	'1  Tomatoes  (cubed)',
	'1  red bell pepper  (sliced)',
	'20 oz spinach leaves',
	'Salt to taste',
	'Fresh Ground Black Pepper to Taste',
	'Chili powder to taste',
	'1 tbsp butter',
	'1 cup white cornmeal',
	'1 quart beef broth',
	'2 lb beef shoulder roast or any other slow cooking beef (I asked my butcher)',
	'1  onion (quartered)',
	'2 cups water (or enough to cover the beef)',
	'1  package lipton recipe secrets onion (recipe soup and dip mix)',
	'1 tsp black pepper',
	'5  bay leaves',
	'2  large bananas',
	'1 6 oz can Dole Pineapple juice',
	'2 tablespoons lemon juice',
	'3/4 cup brown sugar',
	'¼ tsp vanilla',
	'½  Large, Yellow Onion  (I used a Vidalia onion)',
	'1/2  Habanero pepper (more or less to taste )',
	'1  Beef bouillon cube',
	'2 tbsp Oil',
	'2 tbsp Tomato paste',
	'¾ tsp Salt',
	'¾ cup Water',
	'½ cup Creamy all natural peanut butter (I prefer Smuckers Brand)',
	'2  cups cassava flour',
	'4 cups water',
	'1 small rotisserie chicken (2.5lb) (grilled, skin removed &amp; deboned, chopped finely)',
	'½ medium yellow onion (very finely diced (almost a paste))',
	'4 stalks green onions (chopped)',
	'5-10 pieces Donne’ peppers (I substituted Bird’s Eye Chilies) (finely chopped, adjust to taste)',
	'6 tbsp fresh lemon juice',
	'½ tsp salt (more or less to taste)',
	'1 tsp lemon powder (optional (if you are not using, replace with 1-2 more Tablespoons of lemon juice))',
	'½ cup unsweetened coconut',
	'3¾ cup all-purpose flour',
	'6 tbsp unsalted butter (cut into cubes (cold) )',
	'1 cup + 2 tbsp boiling water (tip: Boil 3 cups of water, then carefully pour 1 cup + 2 tbsp of it into your mixing bowl)',
	'1 tsp salt',
	'2 tablespoons olive oil',
	'¼  yellow onion (finely chopped )',
	'2 cups Arborio rice',
	'½ tsp salt',
	'¼ tsp black pepper',
	'1 cup ragù',
	'1 cup chicken stock (or water)',
	'½ cup grated Pecorino Romano (or Parmesan)',
	'3  eggs',
	'6 oz mozzarella (cut into small strips)',
	'3  eggs',
	'2 cups seasoned breadcrumbs',
	'vegetable oil (for frying)',
	'1 loaf crusty bread (cut into slices)',
	'1 clove garlic (whole)',
	'2  roma tomatoes',
	'2 tbsp olive oil',
	'1 tsp flakey sea salt',
	'4 medium Flour Tortillas ( 5.5”)',
	'2-4 pieces Ham',
	'2 cups Oaxaca Cheese (shredded)',
	'Guacamole',
	'Pickled Red Onions',
	'Pico de Gallo',
	'16 oz dried chickpeas (soaked in water for 16 hours (do not use canned chickpeas))',
	'1 cup parsley (roughly chopped & stems removed)',
	'½ cup cilantro (roughly chopped & stems removed)',
	'1  yellow onion (roughly chopped)',
	'5 large  garlic cloves',
	'1 tsp salt',
	'¼ tsp pepper',
	'2 tsp ground cumin',
	'½ tsp coriander',
	'⅛ - ¼ tsp cayenne pepper (depending on preference)',
	'1 tsp baking powder',
	'vegetable oil for frying',
	'8 slices plain white bread (crusts cut off)',
	'8 slices fresh mozzarella (½” thick)',
	'2  eggs',
	'¼ tsp salt',
	'1 pinch black pepper',
	'¾ cup Italian breadcrumbs',
	'vegetable oil (for frying)',
	'2 ½ lb red bell peppers (6.6 lb)',
	'¾ lb eggplant (2 lb)',
	'3  garlic cloves',
	'¼ cup sunflower oil',
	'1 Tbsp white vinegar',
	'1 tsp salt',
	'½ tsp granulated sugar',
	'2.5 lb chicken thigh (fat trimmed off and cut into 1” cubes)',
	'½ cup coconut milk',
	'2 tbsp soy sauce',
	'1 tsp curry powder',
	'¼ tsp turmeric',
	'¼ tsp ground ginger',
	'1 tsp chopped garlic',
	'1 tbsp brown sugar',
	'1 tbsp fish sauce',
	'1 tbsp lime juice',
	'⅓ cup peanut butter',
	'1 tbsp soy sauce',
	'1 Tbsp brown sugar',
	'½ Tbsp freshly chopped ginger',
	'½ tbsp fish sauce (if you don’t want to buy another ingredient, you can substitute this with more soy sauce)',
	'1 tsp rice vinegar',
	'1/2 tsp chili paste to taste',
	'¼ cup water',
	'4 oz Halloumi cheese',
	'2 tsp Olive oil',
	'Watermelon (cubed for serving)',
	'Mint (for serving)',
	'½ cup walnut pieces (unroasted, unsalted )',
	'2 cups fresh basil',
	'¼ cup Parmesan cheese',
	'Juice of ½ lemon',
	'2 tsp Garlic',
	'½ tsp salt',
	'1/4 cup + 2-3 tbsp  olive oil',
	'7 oz snails (1 can)',
	'1  shallot ( finely diced)',
	'10 tbsp Butter  (softened)',
	'3 tsp Garlic  (minced)',
	'¼ cup Parsley ( chopped)',
	'1 tbsp white wine',
	'2 tbsp Breadcrumbs',
	'1  french baguette',
	'24  Empty Snail Shells (optional for serving)',
	'6 tbsp unsalted butter (divided)',
	'2  shallots (finely diced)',
	'3  garlic cloves (minced)',
	'Salt (to taste)',
	'1½ cups dry white wine (I used chardonnay)',
	'1 ½ lb fresh mussels  (cleaned (instructions below) )',
	'1 handful  parsley (chopped)',
	'2 lbs eggplants (about 2 eggplants total)',
	'2 tbsp olive oil  (+ more for final touches)',
	'¼ cup tahini',
	'2 cloves garlic (chopped)',
	'2 tbsp lemon juice',
	'¾ tsp kosher salt',
	'¼ tsp black pepper',
	'2 tbsp parsley',
	'¼  Paprika',
	'1  Nori Seaweed Sheet (cut in half)',
	'¾ cup sushi rice (Cooked )',
	'½  Avocado',
	'1  Imitation crab stick',
	'2 pieces Cucumber (thinly sliced )',
	'3 slices Sushi-grade salmon',
	'3 slices Sushi-grade tuna',
	'1  Mango (thinly sliced)',
	'2 tsp kosher salt',
	'3 cups masa harina',
	'2 ¾ cup water',
	'1 ½ cups Quesillo Cheese (can sub shredded mozzarella)',
	'Vegetable oil for cooking',
	'4 Half  Nori Sheets',
	'½  English Cucumber (cut into thin strips)',
	'8  Shrimp Tempura (prepared according to package instructions)',
	'8 tsp Tobiko',
	'2 cups sushi rice (prepared )',
	'2  avocados',
	'4 tsp sriracha mayo (or more to taste)',
	'2 tsp black sesame seeds',
	'Unagi Sauce (for serving)',
	'¼ cup water',
	'2 tsp rice vinegar',
	'1 cup warm water (divided)',
	'1 tsp granulated sugar',
	'1  package (2 ¼ tsp Active Dry Yeast)',
	'3 cups all purpose flour',
	'2 tbsp dry powdered milk',
	'1 tsp salt',
	'¼ cup olive oil',
	'1 lb ground beef',
	'1  onion (finely diced)',
	'1 tbsp Tomato paste',
	'1 tbsp pepper paste',
	'2   tomatoes (finely diced with seeds removed)',
	'1 tbsp pomegranate molasses',
	'½ tsp Salt',
	'¼ tsp black pepper',
	'1 tbsp 7 Spice',
	'½ cup parsley (finely chopped )',
	'8 oz dry rotini noodles',
	'1 cup Italian dressing',
	'2 cups chicken broth',
	'1  orange bell pepper (chopped)',
	'1 cup feta cheese (crumbled )',
	'1 cup cherry tomatoes (halved )',
	'3 oz salami (cut into pieces)',
	'1  cucumber (peeled and diced)',
	'1/2  green apple (cubed)',
	'¼ cup green olives (chopped)',
	'¼ cup pistachios (chopped)',
	'¼ cup parsley (chopped)',
	'8  mint leaves (chopped)',
	'3 tbsp olive oil',
	'1 ½ tbsp white wine vinegar',
	'¼ tsp sea salt',
	'⅛ tsp black pepper',
	'⅛ tsp paprika',
	'8 oz cream cheese (quark cheese if you can find it, softened to room temperature)',
	'4 tbsp unsalted butter (softened to room temperature)',
	'½ tbsp dijon mustard',
	'1 tbsp capers',
	'1 tsp Caraway seeds',
	'2 tbsp white onion (minced)',
	'2 stalks green onions (chopped)',
	'½ tbsp paprika',
	'½ tsp salt',
	'⅛ tsp black pepper',
	'16 oz cream cheese (softened)',
	'8 oz crab meat',
	'4  scallions (chopped)',
	'2/3 teaspoon salt',
	'1/3 teaspoon garlic powder',
	'1/4 teaspoon onion powder',
	'1  egg',
	'1  package of wonton wrappers (thawed)',
	'Vegetable Oil for frying',
	'2  avocados',
	'¼ cup yellow onion (diced)',
	'1  lime (juiced)',
	'2 tbsp Cilantro (chopped)',
	'¾ tsp Salt',
	'1  Roma Tomato (diced)',
	'1  Jalapeno (diced)',
	'1 8 oz block Feta Cheese',
	'1-2 sheets Phyllo Dough (thawed according to the package instructions)',
	'⅓ cup Olive Oil (more or less depending on the size of your cast iron skillet)',
	'1 tbsp (or more)  Honey',
	'1 tsp Sesame Seeds',
	'1 Cup English Cucumber (peeled and shredded (about 1 large cucumber))',
	'1 1/2 cups Greek Yogurt',
	'½ tsp Kosher Salt',
	'2 tsp Garlic (minced )',
	'1 tbsp Lemon Juice',
	'2 tbsp Olive Oil',
	'1 tbsp Fresh Dill (minced)',
	'1 1/2 lbs Chicken feet',
	'1 tbsp distilled white vinegar',
	'1 tbsp honey',
	'1 tbsp soy sauce',
	'Sunflower oil to fry',
	'1 tbsp brown sugar',
	'4 tbsp soy sauce',
	'2 tbsp oyster sauce',
	'1 1/3 tsp garlic (chopped )',
	'1/2 tsp ginger powder',
	'1/2 tsp cinnamon',
	'4 tbsp water',
	'1 tsp cornstarch',
	'1 tsp chili paste',
	'½  lime (for juice )',
	'5 oz brie cheese (or camembert)',
	'4 oz cream cheese (can also do laughing cow etc)',
	'3 oz butter',
	'½  small sweet onion (finely diced)',
	'½ tbsp Paprika',
	'½ tsp Caraway seeds',
	'2 tbsp wheat beer (I use Blue Moon)',
	'Soft Pretzels for Dipping',
	'½ cup red onion (finely diced)',
	'1  jalapeno (finely diced)',
	'1 cup Roma tomatoes (finely diced (about 2 Roma tomatoes))',
	'1 15 oz can corn ( drained)',
	'1 20 oz can  pineapple tidbits (cut each tidbit into thirds)',
	'½ cup cilantro (chopped)',
	'Juice of ½ of a lime',
	'¾ tsp salt',
	'2 tbsp sesame oil',
	'1 1/4 cup mung bean sprouts',
	'1/2 cup mushrooms',
	'½ cup chicken (cooked (I used rotisserie chicken))',
	'½ cup bamboo shoots (sliced)',
	'½ cup green onions (cut into rounds)',
	'1 tsp chinese 5 spice',
	'An egg for egg wash',
	'Oil for frying (vegetable or sunflower oil)',
	'Egg roll wraps',
	'1 tbsp olive oil',
	'1 lb beef chuck (chopped into tiny bits)',
	'5 tbsp butter',
	'1  Small Onion  (diced)',
	'3/4 tsp Salt',
	'1/4  tsp Fresh Ground Black Pepper to Taste',
	'9 tbsp  All Purpose flour (divided)',
	'1 quart (4 cups) Beef broth',
	'1/2 cup water',
	'5  Idaho Potatoes',
	'1  Container Sunflower Oil for deep frying',
	'Sea Salt',
	'10  oz Cheese curds',
	'1 cup sour cream',
	'1  .7 oz pack of dry Italian Salad Dressing and Recipe Packet (I used Good Seasons Brand)',
	'5  idaho potatoes',
	'1  container sunflower oil for deep frying',
	'Sea salt',
	'Paper to make serving cones',
	'1 cup mayonnaise',
	'2 tbsp tomato paste',
	'1 tbsp green bell pepper',
	'1 tbsp red bell pepper',
	'1 tsp onion powder',
	'1 tsp garlic powder',
	'1 tbsp lemon juice',
	'¼ tsp salt',
	'2 tbsp onions (finely chopped)',
];
